// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/services/call_audio_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:typed_data' as _i14;

import 'package:audioplayers/audioplayers.dart' as _i11;
import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:oasis/features/messages/data/signal/signal_service.dart'
    as _i21;
import 'package:supabase/supabase.dart' as _i9;
import 'package:webrtc_interface/src/enums.dart' as _i17;
import 'package:webrtc_interface/src/media_stream.dart' as _i2;
import 'package:webrtc_interface/src/media_stream_track.dart' as _i3;
import 'package:webrtc_interface/src/rtc_data_channel.dart' as _i5;
import 'package:webrtc_interface/src/rtc_dtmf_sender.dart' as _i6;
import 'package:webrtc_interface/src/rtc_ice_candidate.dart' as _i18;
import 'package:webrtc_interface/src/rtc_peerconnection.dart' as _i15;
import 'package:webrtc_interface/src/rtc_rtp_receiver.dart' as _i16;
import 'package:webrtc_interface/src/rtc_rtp_sender.dart' as _i7;
import 'package:webrtc_interface/src/rtc_rtp_transceiver.dart' as _i8;
import 'package:webrtc_interface/src/rtc_session_description.dart' as _i4;
import 'package:webrtc_interface/src/rtc_stats_report.dart' as _i20;
import 'package:webrtc_interface/src/rtc_track_event.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMediaStream_0 extends _i1.SmartFake implements _i2.MediaStream {
  _FakeMediaStream_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaStreamTrack_1 extends _i1.SmartFake
    implements _i3.MediaStreamTrack {
  _FakeMediaStreamTrack_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCSessionDescription_2 extends _i1.SmartFake
    implements _i4.RTCSessionDescription {
  _FakeRTCSessionDescription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCDataChannel_3 extends _i1.SmartFake
    implements _i5.RTCDataChannel {
  _FakeRTCDataChannel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCDTMFSender_4 extends _i1.SmartFake implements _i6.RTCDTMFSender {
  _FakeRTCDTMFSender_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCRtpSender_5 extends _i1.SmartFake implements _i7.RTCRtpSender {
  _FakeRTCRtpSender_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRTCRtpTransceiver_6 extends _i1.SmartFake
    implements _i8.RTCRtpTransceiver {
  _FakeRTCRtpTransceiver_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_7 extends _i1.SmartFake
    implements _i9.FunctionsClient {
  _FakeFunctionsClient_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_8 extends _i1.SmartFake
    implements _i9.SupabaseStorageClient {
  _FakeSupabaseStorageClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_9 extends _i1.SmartFake
    implements _i9.RealtimeClient {
  _FakeRealtimeClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_10 extends _i1.SmartFake
    implements _i9.PostgrestClient {
  _FakePostgrestClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_11 extends _i1.SmartFake implements _i9.GoTrueClient {
  _FakeGoTrueClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_12 extends _i1.SmartFake
    implements _i9.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_13 extends _i1.SmartFake
    implements _i9.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_14<T1> extends _i1.SmartFake
    implements _i9.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_15 extends _i1.SmartFake
    implements _i9.RealtimeChannel {
  _FakeRealtimeChannel_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCiphertextMessage_16 extends _i1.SmartFake
    implements _i10.CiphertextMessage {
  _FakeCiphertextMessage_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioCache_17 extends _i1.SmartFake implements _i11.AudioCache {
  _FakeAudioCache_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompleter_18<T> extends _i1.SmartFake implements _i12.Completer<T> {
  _FakeCompleter_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStream extends _i1.Mock implements _i2.MediaStream {
  MockMediaStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get ownerTag =>
      (super.noSuchMethod(
            Invocation.getter(#ownerTag),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#ownerTag),
            ),
          )
          as String);

  @override
  set onAddTrack(dynamic Function(_i3.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAddTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoveTrack(dynamic Function(_i3.MediaStreamTrack)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoveTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> getMediaTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getMediaTracks, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addTrack(
    _i3.MediaStreamTrack? track, {
    bool? addToNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track], {#addToNative: addToNative}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeTrack(
    _i3.MediaStreamTrack? track, {
    bool? removeFromNative = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeTrack,
              [track],
              {#removeFromNative: removeFromNative},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<_i3.MediaStreamTrack> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: <_i3.MediaStreamTrack>[],
          )
          as List<_i3.MediaStreamTrack>);

  @override
  List<_i3.MediaStreamTrack> getAudioTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioTracks, []),
            returnValue: <_i3.MediaStreamTrack>[],
          )
          as List<_i3.MediaStreamTrack>);

  @override
  List<_i3.MediaStreamTrack> getVideoTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoTracks, []),
            returnValue: <_i3.MediaStreamTrack>[],
          )
          as List<_i3.MediaStreamTrack>);

  @override
  _i3.MediaStreamTrack? getTrackById(String? trackId) =>
      (super.noSuchMethod(Invocation.method(#getTrackById, [trackId]))
          as _i3.MediaStreamTrack?);

  @override
  _i12.Future<_i2.MediaStream> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i12.Future<_i2.MediaStream>.value(
              _FakeMediaStream_0(this, Invocation.method(#clone, [])),
            ),
          )
          as _i12.Future<_i2.MediaStream>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [MediaStreamTrack].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaStreamTrack extends _i1.Mock implements _i3.MediaStreamTrack {
  MockMediaStreamTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);

  @override
  set onMute(_i3.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onUnMute(_i3.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onUnMute, value),
    returnValueForMissingStub: null,
  );

  @override
  set onEnded(_i3.StreamTrackCallback? value) => super.noSuchMethod(
    Invocation.setter(#onEnded, value),
    returnValueForMissingStub: null,
  );

  @override
  set enabled(bool? b) => super.noSuchMethod(
    Invocation.setter(#enabled, b),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getConstraints() =>
      (super.noSuchMethod(
            Invocation.method(#getConstraints, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<void> applyConstraints([Map<String, dynamic>? constraints]) =>
      (super.noSuchMethod(
            Invocation.method(#applyConstraints, [constraints]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.MediaStreamTrack> clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _i12.Future<_i3.MediaStreamTrack>.value(
              _FakeMediaStreamTrack_1(this, Invocation.method(#clone, [])),
            ),
          )
          as _i12.Future<_i3.MediaStreamTrack>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  Map<String, dynamic> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<bool> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> adaptRes(int? width, int? height) =>
      (super.noSuchMethod(
            Invocation.method(#adaptRes, [width, height]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void enableSpeakerphone(bool? enable) => super.noSuchMethod(
    Invocation.method(#enableSpeakerphone, [enable]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i14.ByteBuffer> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i12.Future<_i14.ByteBuffer>.value(
              _i13.dummyValue<_i14.ByteBuffer>(
                this,
                Invocation.method(#captureFrame, []),
              ),
            ),
          )
          as _i12.Future<_i14.ByteBuffer>);

  @override
  _i12.Future<bool> hasTorch() =>
      (super.noSuchMethod(
            Invocation.method(#hasTorch, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> setTorch(bool? torch) =>
      (super.noSuchMethod(
            Invocation.method(#setTorch, [torch]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [RTCPeerConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockRTCPeerConnection extends _i1.Mock implements _i15.RTCPeerConnection {
  MockRTCPeerConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get getConfiguration =>
      (super.noSuchMethod(
            Invocation.getter(#getConfiguration),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<List<_i7.RTCRtpSender>> get senders =>
      (super.noSuchMethod(
            Invocation.getter(#senders),
            returnValue: _i12.Future<List<_i7.RTCRtpSender>>.value(
              <_i7.RTCRtpSender>[],
            ),
          )
          as _i12.Future<List<_i7.RTCRtpSender>>);

  @override
  _i12.Future<List<_i16.RTCRtpReceiver>> get receivers =>
      (super.noSuchMethod(
            Invocation.getter(#receivers),
            returnValue: _i12.Future<List<_i16.RTCRtpReceiver>>.value(
              <_i16.RTCRtpReceiver>[],
            ),
          )
          as _i12.Future<List<_i16.RTCRtpReceiver>>);

  @override
  _i12.Future<List<_i8.RTCRtpTransceiver>> get transceivers =>
      (super.noSuchMethod(
            Invocation.getter(#transceivers),
            returnValue: _i12.Future<List<_i8.RTCRtpTransceiver>>.value(
              <_i8.RTCRtpTransceiver>[],
            ),
          )
          as _i12.Future<List<_i8.RTCRtpTransceiver>>);

  @override
  set onSignalingState(dynamic Function(_i17.RTCSignalingState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSignalingState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionState(dynamic Function(_i17.RTCPeerConnectionState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onIceGatheringState(dynamic Function(_i17.RTCIceGatheringState)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onIceGatheringState, value),
        returnValueForMissingStub: null,
      );

  @override
  set onIceConnectionState(
    dynamic Function(_i17.RTCIceConnectionState)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onIceConnectionState, value),
    returnValueForMissingStub: null,
  );

  @override
  set onIceCandidate(dynamic Function(_i18.RTCIceCandidate)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onIceCandidate, value),
        returnValueForMissingStub: null,
      );

  @override
  set onAddStream(dynamic Function(_i2.MediaStream)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAddStream, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoveStream(dynamic Function(_i2.MediaStream)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoveStream, value),
        returnValueForMissingStub: null,
      );

  @override
  set onAddTrack(
    dynamic Function(_i2.MediaStream, _i3.MediaStreamTrack)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onAddTrack, value),
    returnValueForMissingStub: null,
  );

  @override
  set onRemoveTrack(
    dynamic Function(_i2.MediaStream, _i3.MediaStreamTrack)? value,
  ) => super.noSuchMethod(
    Invocation.setter(#onRemoveTrack, value),
    returnValueForMissingStub: null,
  );

  @override
  set onDataChannel(dynamic Function(_i5.RTCDataChannel)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onDataChannel, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRenegotiationNeeded(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onRenegotiationNeeded, value),
    returnValueForMissingStub: null,
  );

  @override
  set onTrack(dynamic Function(_i19.RTCTrackEvent)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onTrack, value),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i17.RTCSignalingState?> getSignalingState() =>
      (super.noSuchMethod(
            Invocation.method(#getSignalingState, []),
            returnValue: _i12.Future<_i17.RTCSignalingState?>.value(),
          )
          as _i12.Future<_i17.RTCSignalingState?>);

  @override
  _i12.Future<_i17.RTCIceGatheringState?> getIceGatheringState() =>
      (super.noSuchMethod(
            Invocation.method(#getIceGatheringState, []),
            returnValue: _i12.Future<_i17.RTCIceGatheringState?>.value(),
          )
          as _i12.Future<_i17.RTCIceGatheringState?>);

  @override
  _i12.Future<_i17.RTCIceConnectionState?> getIceConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#getIceConnectionState, []),
            returnValue: _i12.Future<_i17.RTCIceConnectionState?>.value(),
          )
          as _i12.Future<_i17.RTCIceConnectionState?>);

  @override
  _i12.Future<_i17.RTCPeerConnectionState?> getConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionState, []),
            returnValue: _i12.Future<_i17.RTCPeerConnectionState?>.value(),
          )
          as _i12.Future<_i17.RTCPeerConnectionState?>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setConfiguration(Map<String, dynamic>? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#setConfiguration, [configuration]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.RTCSessionDescription> createOffer([
    Map<String, dynamic>? constraints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [constraints]),
            returnValue: _i12.Future<_i4.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_2(
                this,
                Invocation.method(#createOffer, [constraints]),
              ),
            ),
          )
          as _i12.Future<_i4.RTCSessionDescription>);

  @override
  _i12.Future<_i4.RTCSessionDescription> createAnswer([
    Map<String, dynamic>? constraints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createAnswer, [constraints]),
            returnValue: _i12.Future<_i4.RTCSessionDescription>.value(
              _FakeRTCSessionDescription_2(
                this,
                Invocation.method(#createAnswer, [constraints]),
              ),
            ),
          )
          as _i12.Future<_i4.RTCSessionDescription>);

  @override
  _i12.Future<void> addStream(_i2.MediaStream? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> removeStream(_i2.MediaStream? stream) =>
      (super.noSuchMethod(
            Invocation.method(#removeStream, [stream]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.RTCSessionDescription?> getLocalDescription() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalDescription, []),
            returnValue: _i12.Future<_i4.RTCSessionDescription?>.value(),
          )
          as _i12.Future<_i4.RTCSessionDescription?>);

  @override
  _i12.Future<void> setLocalDescription(
    _i4.RTCSessionDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setLocalDescription, [description]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.RTCSessionDescription?> getRemoteDescription() =>
      (super.noSuchMethod(
            Invocation.method(#getRemoteDescription, []),
            returnValue: _i12.Future<_i4.RTCSessionDescription?>.value(),
          )
          as _i12.Future<_i4.RTCSessionDescription?>);

  @override
  _i12.Future<void> setRemoteDescription(
    _i4.RTCSessionDescription? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRemoteDescription, [description]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addCandidate(_i18.RTCIceCandidate? candidate) =>
      (super.noSuchMethod(
            Invocation.method(#addCandidate, [candidate]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i20.StatsReport>> getStats([_i3.MediaStreamTrack? track]) =>
      (super.noSuchMethod(
            Invocation.method(#getStats, [track]),
            returnValue: _i12.Future<List<_i20.StatsReport>>.value(
              <_i20.StatsReport>[],
            ),
          )
          as _i12.Future<List<_i20.StatsReport>>);

  @override
  List<_i2.MediaStream?> getLocalStreams() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalStreams, []),
            returnValue: <_i2.MediaStream?>[],
          )
          as List<_i2.MediaStream?>);

  @override
  List<_i2.MediaStream?> getRemoteStreams() =>
      (super.noSuchMethod(
            Invocation.method(#getRemoteStreams, []),
            returnValue: <_i2.MediaStream?>[],
          )
          as List<_i2.MediaStream?>);

  @override
  _i12.Future<_i5.RTCDataChannel> createDataChannel(
    String? label,
    _i5.RTCDataChannelInit? dataChannelDict,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createDataChannel, [label, dataChannelDict]),
            returnValue: _i12.Future<_i5.RTCDataChannel>.value(
              _FakeRTCDataChannel_3(
                this,
                Invocation.method(#createDataChannel, [label, dataChannelDict]),
              ),
            ),
          )
          as _i12.Future<_i5.RTCDataChannel>);

  @override
  _i12.Future<void> restartIce() =>
      (super.noSuchMethod(
            Invocation.method(#restartIce, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i6.RTCDTMFSender createDtmfSender(_i3.MediaStreamTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#createDtmfSender, [track]),
            returnValue: _FakeRTCDTMFSender_4(
              this,
              Invocation.method(#createDtmfSender, [track]),
            ),
          )
          as _i6.RTCDTMFSender);

  @override
  _i12.Future<List<_i7.RTCRtpSender>> getSenders() =>
      (super.noSuchMethod(
            Invocation.method(#getSenders, []),
            returnValue: _i12.Future<List<_i7.RTCRtpSender>>.value(
              <_i7.RTCRtpSender>[],
            ),
          )
          as _i12.Future<List<_i7.RTCRtpSender>>);

  @override
  _i12.Future<List<_i16.RTCRtpReceiver>> getReceivers() =>
      (super.noSuchMethod(
            Invocation.method(#getReceivers, []),
            returnValue: _i12.Future<List<_i16.RTCRtpReceiver>>.value(
              <_i16.RTCRtpReceiver>[],
            ),
          )
          as _i12.Future<List<_i16.RTCRtpReceiver>>);

  @override
  _i12.Future<List<_i8.RTCRtpTransceiver>> getTransceivers() =>
      (super.noSuchMethod(
            Invocation.method(#getTransceivers, []),
            returnValue: _i12.Future<List<_i8.RTCRtpTransceiver>>.value(
              <_i8.RTCRtpTransceiver>[],
            ),
          )
          as _i12.Future<List<_i8.RTCRtpTransceiver>>);

  @override
  _i12.Future<_i7.RTCRtpSender> addTrack(
    _i3.MediaStreamTrack? track, [
    _i2.MediaStream? stream,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#addTrack, [track, stream]),
            returnValue: _i12.Future<_i7.RTCRtpSender>.value(
              _FakeRTCRtpSender_5(
                this,
                Invocation.method(#addTrack, [track, stream]),
              ),
            ),
          )
          as _i12.Future<_i7.RTCRtpSender>);

  @override
  _i12.Future<bool> removeTrack(_i7.RTCRtpSender? sender) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrack, [sender]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<_i8.RTCRtpTransceiver> addTransceiver({
    _i3.MediaStreamTrack? track,
    _i17.RTCRtpMediaType? kind,
    _i8.RTCRtpTransceiverInit? init,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTransceiver, [], {
              #track: track,
              #kind: kind,
              #init: init,
            }),
            returnValue: _i12.Future<_i8.RTCRtpTransceiver>.value(
              _FakeRTCRtpTransceiver_6(
                this,
                Invocation.method(#addTransceiver, [], {
                  #track: track,
                  #kind: kind,
                  #init: init,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.RTCRtpTransceiver>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i9.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_7(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i9.FunctionsClient);

  @override
  _i9.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_8(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i9.SupabaseStorageClient);

  @override
  _i9.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_9(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i9.RealtimeClient);

  @override
  _i9.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_10(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i9.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i9.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_11(this, Invocation.getter(#auth)),
          )
          as _i9.GoTrueClient);

  @override
  set functions(_i9.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i9.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i9.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i9.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i9.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_12(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i9.SupabaseQueryBuilder);

  @override
  _i9.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_13(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i9.SupabaseQuerySchema);

  @override
  _i9.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_14<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i9.PostgrestFilterBuilder<T>);

  @override
  _i9.RealtimeChannel channel(
    String? name, {
    _i9.RealtimeChannelConfig? opts = const _i9.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_15(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i9.RealtimeChannel);

  @override
  List<_i9.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i9.RealtimeChannel>[],
          )
          as List<_i9.RealtimeChannel>);

  @override
  _i12.Future<String> removeChannel(_i9.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [SignalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignalService extends _i1.Mock implements _i21.SignalService {
  MockSignalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i12.Future<bool> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> clearData() =>
      (super.noSuchMethod(
            Invocation.method(#clearData, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> forceRefreshBundle(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshBundle, [remoteUserId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i10.CiphertextMessage> encryptMessage(
    String? recipientId,
    String? plaintext, {
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [recipientId, plaintext],
              {#deviceId: deviceId},
            ),
            returnValue: _i12.Future<_i10.CiphertextMessage>.value(
              _FakeCiphertextMessage_16(
                this,
                Invocation.method(
                  #encryptMessage,
                  [recipientId, plaintext],
                  {#deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i12.Future<_i10.CiphertextMessage>);

  @override
  _i12.Future<String> decryptMessage(
    String? senderId,
    String? base64Ciphertext,
    int? type, {
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptMessage,
              [senderId, base64Ciphertext, type],
              {#deviceId: deviceId},
            ),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(
                  #decryptMessage,
                  [senderId, base64Ciphertext, type],
                  {#deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i12.Future<String>);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i11.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AudioCache get audioCache =>
      (super.noSuchMethod(
            Invocation.getter(#audioCache),
            returnValue: _FakeAudioCache_17(
              this,
              Invocation.getter(#audioCache),
            ),
          )
          as _i11.AudioCache);

  @override
  String get playerId =>
      (super.noSuchMethod(
            Invocation.getter(#playerId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#playerId),
            ),
          )
          as String);

  @override
  double get volume =>
      (super.noSuchMethod(Invocation.getter(#volume), returnValue: 0.0)
          as double);

  @override
  double get balance =>
      (super.noSuchMethod(Invocation.getter(#balance), returnValue: 0.0)
          as double);

  @override
  double get playbackRate =>
      (super.noSuchMethod(Invocation.getter(#playbackRate), returnValue: 0.0)
          as double);

  @override
  _i11.PlayerMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i11.PlayerMode.mediaPlayer,
          )
          as _i11.PlayerMode);

  @override
  _i11.ReleaseMode get releaseMode =>
      (super.noSuchMethod(
            Invocation.getter(#releaseMode),
            returnValue: _i11.ReleaseMode.release,
          )
          as _i11.ReleaseMode);

  @override
  _i11.PlayerState get desiredState =>
      (super.noSuchMethod(
            Invocation.getter(#desiredState),
            returnValue: _i11.PlayerState.stopped,
          )
          as _i11.PlayerState);

  @override
  _i11.PlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.PlayerState.stopped,
          )
          as _i11.PlayerState);

  @override
  _i12.Completer<void> get creatingCompleter =>
      (super.noSuchMethod(
            Invocation.getter(#creatingCompleter),
            returnValue: _FakeCompleter_18<void>(
              this,
              Invocation.getter(#creatingCompleter),
            ),
          )
          as _i12.Completer<void>);

  @override
  _i12.Stream<_i11.AudioEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i12.Stream<_i11.AudioEvent>.empty(),
          )
          as _i12.Stream<_i11.AudioEvent>);

  @override
  _i12.Stream<_i11.PlayerState> get onPlayerStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerStateChanged),
            returnValue: _i12.Stream<_i11.PlayerState>.empty(),
          )
          as _i12.Stream<_i11.PlayerState>);

  @override
  _i12.Stream<Duration> get onPositionChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPositionChanged),
            returnValue: _i12.Stream<Duration>.empty(),
          )
          as _i12.Stream<Duration>);

  @override
  _i12.Stream<Duration> get onDurationChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onDurationChanged),
            returnValue: _i12.Stream<Duration>.empty(),
          )
          as _i12.Stream<Duration>);

  @override
  _i12.Stream<void> get onPlayerComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerComplete),
            returnValue: _i12.Stream<void>.empty(),
          )
          as _i12.Stream<void>);

  @override
  _i12.Stream<void> get onSeekComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onSeekComplete),
            returnValue: _i12.Stream<void>.empty(),
          )
          as _i12.Stream<void>);

  @override
  _i12.Stream<String> get onLog =>
      (super.noSuchMethod(
            Invocation.getter(#onLog),
            returnValue: _i12.Stream<String>.empty(),
          )
          as _i12.Stream<String>);

  @override
  set audioCache(_i11.AudioCache? value) => super.noSuchMethod(
    Invocation.setter(#audioCache, value),
    returnValueForMissingStub: null,
  );

  @override
  set desiredState(_i11.PlayerState? value) => super.noSuchMethod(
    Invocation.setter(#desiredState, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i11.PlayerState? state) => super.noSuchMethod(
    Invocation.setter(#state, state),
    returnValueForMissingStub: null,
  );

  @override
  set positionUpdater(_i11.PositionUpdater? positionUpdater) =>
      super.noSuchMethod(
        Invocation.setter(#positionUpdater, positionUpdater),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> play(
    _i11.Source? source, {
    double? volume,
    double? balance,
    _i11.AudioContext? ctx,
    Duration? position,
    _i11.PlayerMode? mode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #play,
              [source],
              {
                #volume: volume,
                #balance: balance,
                #ctx: ctx,
                #position: position,
                #mode: mode,
              },
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setAudioContext(_i11.AudioContext? ctx) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioContext, [ctx]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setPlayerMode(_i11.PlayerMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setPlayerMode, [mode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> release() =>
      (super.noSuchMethod(
            Invocation.method(#release, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setBalance(double? balance) =>
      (super.noSuchMethod(
            Invocation.method(#setBalance, [balance]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setReleaseMode(_i11.ReleaseMode? releaseMode) =>
      (super.noSuchMethod(
            Invocation.method(#setReleaseMode, [releaseMode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setPlaybackRate(double? playbackRate) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackRate, [playbackRate]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSource(_i11.Source? source) =>
      (super.noSuchMethod(
            Invocation.method(#setSource, [source]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSourceUrl(String? url, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceUrl, [url], {#mimeType: mimeType}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSourceDeviceFile(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSourceDeviceFile,
              [path],
              {#mimeType: mimeType},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSourceAsset(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceAsset, [path], {#mimeType: mimeType}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSourceBytes(_i14.Uint8List? bytes, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceBytes, [bytes], {#mimeType: mimeType}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Duration?> getDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, []),
            returnValue: _i12.Future<Duration?>.value(),
          )
          as _i12.Future<Duration?>);

  @override
  _i12.Future<Duration?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i12.Future<Duration?>.value(),
          )
          as _i12.Future<Duration?>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}
