// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/services/messaging_refactor_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i9;

import 'package:encrypt/encrypt.dart' as _i2;
import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:oasis/models/conversation.dart' as _i14;
import 'package:oasis/models/message.dart' as _i6;
import 'package:oasis/services/chat_decryption_service.dart' as _i12;
import 'package:oasis/services/chat_media_service.dart' as _i16;
import 'package:oasis/services/chat_messaging_service.dart' as _i15;
import 'package:oasis/services/conversation_service.dart' as _i13;
import 'package:oasis/services/encryption_service.dart' as _i3;
import 'package:oasis/services/key_management_service.dart' as _i8;
import 'package:oasis/services/message_operations_service.dart' as _i17;
import 'package:oasis/services/signal/signal_service.dart' as _i10;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKey_0 extends _i1.SmartFake implements _i2.Key {
  _FakeKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedMessage_1 extends _i1.SmartFake
    implements _i3.EncryptedMessage {
  _FakeEncryptedMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCiphertextMessage_2 extends _i1.SmartFake
    implements _i4.CiphertextMessage {
  _FakeCiphertextMessage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_3 extends _i1.SmartFake
    implements _i5.FunctionsClient {
  _FakeFunctionsClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_4 extends _i1.SmartFake
    implements _i5.SupabaseStorageClient {
  _FakeSupabaseStorageClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_5 extends _i1.SmartFake
    implements _i5.RealtimeClient {
  _FakeRealtimeClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_6 extends _i1.SmartFake
    implements _i5.PostgrestClient {
  _FakePostgrestClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_7 extends _i1.SmartFake implements _i5.GoTrueClient {
  _FakeGoTrueClient_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_8 extends _i1.SmartFake
    implements _i5.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_9 extends _i1.SmartFake
    implements _i5.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_10<T1> extends _i1.SmartFake
    implements _i5.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_11 extends _i1.SmartFake
    implements _i5.RealtimeChannel {
  _FakeRealtimeChannel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_12 extends _i1.SmartFake implements _i6.Message {
  _FakeMessage_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i3.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i7.Future<_i8.EncryptionStatus> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<_i8.EncryptionStatus>.value(
              _i8.EncryptionStatus.ready,
            ),
          )
          as _i7.Future<_i8.EncryptionStatus>);

  @override
  _i7.Future<bool> setupEncryption() =>
      (super.noSuchMethod(
            Invocation.method(#setupEncryption, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> restoreKeys() =>
      (super.noSuchMethod(
            Invocation.method(#restoreKeys, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i2.Key generateAESKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateAESKey, []),
            returnValue: _FakeKey_0(
              this,
              Invocation.method(#generateAESKey, []),
            ),
          )
          as _i2.Key);

  @override
  _i9.Uint8List encryptData(_i9.Uint8List? data, _i2.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#encryptData, [data, key]),
            returnValue: _i9.Uint8List(0),
          )
          as _i9.Uint8List);

  @override
  _i9.Uint8List? decryptData(_i9.Uint8List? combinedData, _i2.Key? key) =>
      (super.noSuchMethod(Invocation.method(#decryptData, [combinedData, key]))
          as _i9.Uint8List?);

  @override
  _i7.Future<_i3.EncryptedMessage> encryptMessage(
    String? content,
    List<String>? recipientPublicKeysPem, {
    _i2.Key? reuseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [content, recipientPublicKeysPem],
              {#reuseKey: reuseKey},
            ),
            returnValue: _i7.Future<_i3.EncryptedMessage>.value(
              _FakeEncryptedMessage_1(
                this,
                Invocation.method(
                  #encryptMessage,
                  [content, recipientPublicKeysPem],
                  {#reuseKey: reuseKey},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.EncryptedMessage>);

  @override
  _i7.Future<String?> decryptMessage(
    String? encryptedContentBase64,
    Map<String, dynamic>? encryptedKeys,
    String? ivBase64,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMessage, [
              encryptedContentBase64,
              encryptedKeys,
              ivBase64,
            ]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> backupSignalIdentity(
    String? identityKeyPairBase64,
    int? registrationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#backupSignalIdentity, [
              identityKeyPairBase64,
              registrationId,
            ]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> restoreSignalIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSignalIdentity, []),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> clearKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearKeys, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SignalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignalService extends _i1.Mock implements _i10.SignalService {
  MockSignalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i7.Future<bool> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> clearData() =>
      (super.noSuchMethod(
            Invocation.method(#clearData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> forceRefreshBundle(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshBundle, [remoteUserId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.CiphertextMessage> encryptMessage(
    String? recipientId,
    String? plaintext, {
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [recipientId, plaintext],
              {#deviceId: deviceId},
            ),
            returnValue: _i7.Future<_i4.CiphertextMessage>.value(
              _FakeCiphertextMessage_2(
                this,
                Invocation.method(
                  #encryptMessage,
                  [recipientId, plaintext],
                  {#deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.CiphertextMessage>);

  @override
  _i7.Future<String> decryptMessage(
    String? senderId,
    String? base64Ciphertext,
    int? type, {
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptMessage,
              [senderId, base64Ciphertext, type],
              {#deviceId: deviceId},
            ),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(
                  #decryptMessage,
                  [senderId, base64Ciphertext, type],
                  {#deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i7.Future<String>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i5.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_3(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i5.FunctionsClient);

  @override
  _i5.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_4(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.SupabaseStorageClient);

  @override
  _i5.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_5(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i5.RealtimeClient);

  @override
  _i5.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_6(this, Invocation.getter(#rest)),
          )
          as _i5.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i5.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_7(this, Invocation.getter(#auth)),
          )
          as _i5.GoTrueClient);

  @override
  set functions(_i5.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i5.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i5.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i5.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_8(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i5.SupabaseQueryBuilder);

  @override
  _i5.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_9(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i5.SupabaseQuerySchema);

  @override
  _i5.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_10<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i5.PostgrestFilterBuilder<T>);

  @override
  _i5.RealtimeChannel channel(
    String? name, {
    _i5.RealtimeChannelConfig? opts = const _i5.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i5.RealtimeChannel);

  @override
  List<_i5.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i5.RealtimeChannel>[],
          )
          as List<_i5.RealtimeChannel>);

  @override
  _i7.Future<String> removeChannel(_i5.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ChatDecryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatDecryptionService extends _i1.Mock
    implements _i12.ChatDecryptionService {
  MockChatDecryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> decryptMessageContent({
    required String? senderId,
    required String? currentUserId,
    required String? content,
    Map<String, String>? encryptedKeys,
    String? iv,
    int? signalMessageType,
    String? signalSenderContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMessageContent, [], {
              #senderId: senderId,
              #currentUserId: currentUserId,
              #content: content,
              #encryptedKeys: encryptedKeys,
              #iv: iv,
              #signalMessageType: signalMessageType,
              #signalSenderContent: signalSenderContent,
            }),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#decryptMessageContent, [], {
                  #senderId: senderId,
                  #currentUserId: currentUserId,
                  #content: content,
                  #encryptedKeys: encryptedKeys,
                  #iv: iv,
                  #signalMessageType: signalMessageType,
                  #signalSenderContent: signalSenderContent,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  String determineMessageType(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#determineMessageType, [data]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#determineMessageType, [data]),
            ),
          )
          as String);
}

/// A class which mocks [ConversationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationService extends _i1.Mock
    implements _i13.ConversationService {
  MockConversationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i14.Conversation>> getConversations({
    required String? userId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #userId: userId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<List<_i14.Conversation>>.value(
              <_i14.Conversation>[],
            ),
          )
          as _i7.Future<List<_i14.Conversation>>);

  @override
  _i7.Future<String> getOrCreateConversation({
    required String? user1Id,
    required String? user2Id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateConversation, [], {
              #user1Id: user1Id,
              #user2Id: user2Id,
            }),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateConversation, [], {
                  #user1Id: user1Id,
                  #user2Id: user2Id,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i5.RealtimeChannel subscribeToConversations({
    required String? userId,
    required dynamic Function(String)? onUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToConversations, [], {
              #userId: userId,
              #onUpdate: onUpdate,
            }),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#subscribeToConversations, [], {
                #userId: userId,
                #onUpdate: onUpdate,
              }),
            ),
          )
          as _i5.RealtimeChannel);

  @override
  _i7.Future<void> updateChatBackground(
    String? conversationId,
    String? backgroundUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateChatBackground, [
              conversationId,
              backgroundUrl,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ChatMessagingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatMessagingService extends _i1.Mock
    implements _i15.ChatMessagingService {
  MockChatMessagingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i6.Message>> getMessages({
    required String? conversationId,
    int? limit = 50,
    int? offset = 0,
    DateTime? sessionStart,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [], {
              #conversationId: conversationId,
              #limit: limit,
              #offset: offset,
              #sessionStart: sessionStart,
            }),
            returnValue: _i7.Future<List<_i6.Message>>.value(<_i6.Message>[]),
          )
          as _i7.Future<List<_i6.Message>>);

  @override
  _i7.Future<_i6.Message> sendMessage({
    required String? conversationId,
    required String? senderId,
    required String? content,
    _i6.MessageType? messageType = _i6.MessageType.text,
    String? mediaUrl,
    String? mediaFileName,
    int? mediaFileSize,
    int? voiceDuration,
    Map<String, String>? encryptedKeys,
    String? iv,
    int? signalMessageType,
    String? signalSenderContent,
    int? whisperMode = 0,
    String? callId,
    String? replyToId,
    String? rippleId,
    String? storyId,
    String? postId,
    Map<String, dynamic>? shareData,
    String? mediaViewMode = 'unlimited',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #senderId: senderId,
              #content: content,
              #messageType: messageType,
              #mediaUrl: mediaUrl,
              #mediaFileName: mediaFileName,
              #mediaFileSize: mediaFileSize,
              #voiceDuration: voiceDuration,
              #encryptedKeys: encryptedKeys,
              #iv: iv,
              #signalMessageType: signalMessageType,
              #signalSenderContent: signalSenderContent,
              #whisperMode: whisperMode,
              #callId: callId,
              #replyToId: replyToId,
              #rippleId: rippleId,
              #storyId: storyId,
              #postId: postId,
              #shareData: shareData,
              #mediaViewMode: mediaViewMode,
            }),
            returnValue: _i7.Future<_i6.Message>.value(
              _FakeMessage_12(
                this,
                Invocation.method(#sendMessage, [], {
                  #conversationId: conversationId,
                  #senderId: senderId,
                  #content: content,
                  #messageType: messageType,
                  #mediaUrl: mediaUrl,
                  #mediaFileName: mediaFileName,
                  #mediaFileSize: mediaFileSize,
                  #voiceDuration: voiceDuration,
                  #encryptedKeys: encryptedKeys,
                  #iv: iv,
                  #signalMessageType: signalMessageType,
                  #signalSenderContent: signalSenderContent,
                  #whisperMode: whisperMode,
                  #callId: callId,
                  #replyToId: replyToId,
                  #rippleId: rippleId,
                  #storyId: storyId,
                  #postId: postId,
                  #shareData: shareData,
                  #mediaViewMode: mediaViewMode,
                }),
              ),
            ),
          )
          as _i7.Future<_i6.Message>);

  @override
  _i7.Future<void> markAsRead({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i5.RealtimeChannel subscribeToMessages({
    required String? conversationId,
    required dynamic Function(_i6.Message)? onNewMessage,
    dynamic Function(String)? onDeleteMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMessages, [], {
              #conversationId: conversationId,
              #onNewMessage: onNewMessage,
              #onDeleteMessage: onDeleteMessage,
            }),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#subscribeToMessages, [], {
                #conversationId: conversationId,
                #onNewMessage: onNewMessage,
                #onDeleteMessage: onDeleteMessage,
              }),
            ),
          )
          as _i5.RealtimeChannel);
}

/// A class which mocks [ChatMediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatMediaService extends _i1.Mock implements _i16.ChatMediaService {
  MockChatMediaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> uploadChatMedia(
    String? filePath, {
    String? folder = 'images',
    _i9.Uint8List? encryptedBytes,
    String? fileExtension,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadChatMedia,
              [filePath],
              {
                #folder: folder,
                #encryptedBytes: encryptedBytes,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadChatMedia,
                  [filePath],
                  {
                    #folder: folder,
                    #encryptedBytes: encryptedBytes,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deleteMediaFromUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMediaFromUrl, [url]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [MessageOperationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageOperationsService extends _i1.Mock
    implements _i17.MessageOperationsService {
  MockMessageOperationsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearChatForMe(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#clearChatForMe, [conversationId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearConversationMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#clearConversationMessages, [conversationId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateTypingStatus(
    String? conversationId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTypingStatus, [
              conversationId,
              userId,
              isTyping,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i5.RealtimeChannel subscribeToReadReceipts({
    required String? conversationId,
    required dynamic Function(String, String, DateTime)? onUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToReadReceipts, [], {
              #conversationId: conversationId,
              #onUpdate: onUpdate,
            }),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#subscribeToReadReceipts, [], {
                #conversationId: conversationId,
                #onUpdate: onUpdate,
              }),
            ),
          )
          as _i5.RealtimeChannel);

  @override
  _i5.RealtimeChannel subscribeToConversationDetails({
    required String? conversationId,
    required dynamic Function(int)? onUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToConversationDetails, [], {
              #conversationId: conversationId,
              #onUpdate: onUpdate,
            }),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#subscribeToConversationDetails, [], {
                #conversationId: conversationId,
                #onUpdate: onUpdate,
              }),
            ),
          )
          as _i5.RealtimeChannel);
}
