platform :osx, '11.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :deterministic_uuids => false

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Load Flutter Pod helper
require File.expand_path(File.join('Flutter', 'ephemeral', 'podhelper.rb'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = File.join(__dir__, 'Flutter')
  eval(File.read(File.join(flutter_application_path, 'ephemeral', 'podhelper.rb')), binding)
end

target 'RunnerTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
