// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAuULD_aCyBaEV5TyVYUC15TcC-GIJKPyE',
//     appId: '1:244356693090:web:3a4c64278c534efd2ea53b',
//     messagingSenderId: '244356693090',
//     projectId: 'morrow-6712f',
//     authDomain: 'morrow-6712f.firebaseapp.com',
//     storageBucket: 'morrow-6712f.firebasestorage.app',
//     measurementId: 'G-Q2FBTY8LD1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCUH_8F75hahrIVl5Ri8SB5aSFMEqYsP_M',
//     appId: '1:244356693090:android:68d113013cd0f70c2ea53b',
//     messagingSenderId: '244356693090',
//     projectId: 'morrow-6712f',
//     storageBucket: 'morrow-6712f.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB2VRe_iCwuRngBAGOPrLF2o2UtWbMzqbE',
//     appId: '1:244356693090:ios:b8d6e9ef1fbcffbc2ea53b',
//     messagingSenderId: '244356693090',
//     projectId: 'morrow-6712f',
//     storageBucket: 'morrow-6712f.firebasestorage.app',
//     iosBundleId: 'com.example.morrow_v2',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB2VRe_iCwuRngBAGOPrLF2o2UtWbMzqbE',
//     appId: '1:244356693090:ios:b8d6e9ef1fbcffbc2ea53b',
//     messagingSenderId: '244356693090',
//     projectId: 'morrow-6712f',
//     storageBucket: 'morrow-6712f.firebasestorage.app',
//     iosBundleId: 'com.example.morrow_v2',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAuULD_aCyBaEV5TyVYUC15TcC-GIJKPyE',
//     appId: '1:244356693090:web:2335af17643d9e372ea53b',
//     messagingSenderId: '244356693090',
//     projectId: 'morrow-6712f',
//     authDomain: 'morrow-6712f.firebaseapp.com',
//     storageBucket: 'morrow-6712f.firebasestorage.app',
//     measurementId: 'G-8T22BFD635',
//   );
// }
