-- Calls Schema for Real-time Voice and Video Calling

-- Call status enum
CREATE TYPE call_status AS ENUM ('pinging', 'active', 'ended', 'missed', 'rejected');

-- Call type enum
CREATE TYPE call_type AS ENUM ('voice', 'video');

-- Calls table
CREATE TABLE calls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    host_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    channel_name TEXT NOT NULL, -- Agora channel name
    status call_status DEFAULT 'pinging',
    type call_type DEFAULT 'voice',
    started_at TIMESTAMPTZ DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    agora_token TEXT, -- Optional: store token if generated by backend
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Call participants table (for group calls and tracking status)
CREATE TABLE call_participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    call_id UUID REFERENCES calls(id) ON DELETE CASCADE,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ,
    left_at TIMESTAMPTZ,
    is_muted BOOLEAN DEFAULT FALSE,
    is_video_on BOOLEAN DEFAULT TRUE,
    is_screen_sharing BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'invited', -- invited, joined, left, declined
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(call_id, user_id)
);

-- Add call_id to messages to link call history in chat
ALTER TABLE messages ADD COLUMN call_id UUID REFERENCES calls(id) ON DELETE SET NULL;

-- Enable RLS
ALTER TABLE calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE call_participants ENABLE ROW LEVEL SECURITY;

-- RLS Policies for calls
CREATE POLICY "Users can see calls they are part of"
    ON calls FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM conversation_participants
            WHERE conversation_id = calls.conversation_id
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can initiate calls in conversations they are part of"
    ON calls FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM conversation_participants
            WHERE conversation_id = conversation_id
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Host can update their call"
    ON calls FOR UPDATE
    USING (host_id = auth.uid());

-- RLS Policies for call_participants
CREATE POLICY "Users can see participants of calls they are part of"
    ON call_participants FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM conversation_participants cp
            JOIN calls c ON c.conversation_id = cp.conversation_id
            WHERE c.id = call_participants.call_id
            AND cp.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can update their own participant status"
    ON call_participants FOR UPDATE
    USING (user_id = auth.uid());

CREATE POLICY "Users can join calls they are invited to"
    ON call_participants FOR INSERT
    WITH CHECK (user_id = auth.uid());

-- Index for performance
CREATE INDEX idx_calls_conversation_id ON calls(conversation_id);
CREATE INDEX idx_calls_status ON calls(status);
CREATE INDEX idx_call_participants_call_id ON call_participants(call_id);
CREATE INDEX idx_call_participants_user_id ON call_participants(user_id);
