-- Add user settings columns to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS data_saver BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS font_size_factor FLOAT DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS high_contrast BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mesh_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS daily_limit_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS mica_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS window_effect TEXT DEFAULT 'mica',
ADD COLUMN IF NOT EXISTS font_family TEXT DEFAULT 'Inter',
ADD COLUMN IF NOT EXISTS feed_layout TEXT DEFAULT 'classic';
