// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/features/calling/call_provider_real_path_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:oasis/features/calling/domain/models/call_entity.dart' as _i2;
import 'package:oasis/features/calling/domain/repositories/call_repository.dart'
    as _i8;
import 'package:oasis/features/messages/data/pq_aura/pq_aura_service.dart'
    as _i10;
import 'package:oasis/services/call_service.dart' as _i4;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCallEntity_0 extends _i1.SmartFake implements _i2.CallEntity {
  _FakeCallEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_10 extends _i1.SmartFake
    implements _i3.GoTrueAdminApi {
  _FakeGoTrueAdminApi_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_11 extends _i1.SmartFake implements _i3.GoTrueMFAApi {
  _FakeGoTrueMFAApi_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_13 extends _i1.SmartFake implements _i3.OAuthResponse {
  _FakeOAuthResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_14 extends _i1.SmartFake
    implements _i3.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_15 extends _i1.SmartFake
    implements _i3.ResendResponse {
  _FakeResendResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_16 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_17 extends _i1.SmartFake implements Object {
  _FakeObject_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetClaimsResponse_18 extends _i1.SmartFake
    implements _i3.GetClaimsResponse {
  _FakeGetClaimsResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallService extends _i1.Mock implements _i4.CallService {
  MockCallService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get isMuted =>
      (super.noSuchMethod(Invocation.getter(#isMuted), returnValue: false)
          as bool);

  @override
  bool get isVideoOn =>
      (super.noSuchMethod(Invocation.getter(#isVideoOn), returnValue: false)
          as bool);

  @override
  bool get isSpeakerphoneOn =>
      (super.noSuchMethod(
            Invocation.getter(#isSpeakerphoneOn),
            returnValue: false,
          )
          as bool);

  @override
  bool get isScreenSharing =>
      (super.noSuchMethod(
            Invocation.getter(#isScreenSharing),
            returnValue: false,
          )
          as bool);

  @override
  List<String> get callSteps =>
      (super.noSuchMethod(
            Invocation.getter(#callSteps),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  set e2eeKey(_i5.Uint8List? value) => super.noSuchMethod(
    Invocation.setter(#e2eeKey, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAnswering(String? callId) => super.noSuchMethod(
    Invocation.method(#setAnswering, [callId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initLocalStream(bool? isVideo) =>
      (super.noSuchMethod(
            Invocation.method(#initLocalStream, [isVideo]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> startSignaling(_i2.CallEntity? call, [_i5.Uint8List? key]) =>
      (super.noSuchMethod(
            Invocation.method(#startSignaling, [call, key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void startIncomingCallListener() => super.noSuchMethod(
    Invocation.method(#startIncomingCallListener, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> endCall() =>
      (super.noSuchMethod(
            Invocation.method(#endCall, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleMute() =>
      (super.noSuchMethod(
            Invocation.method(#toggleMute, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleVideo() =>
      (super.noSuchMethod(
            Invocation.method(#toggleVideo, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleScreenShare() =>
      (super.noSuchMethod(
            Invocation.method(#toggleScreenShare, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void toggleSpeakerphone() => super.noSuchMethod(
    Invocation.method(#toggleSpeakerphone, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> startRingtone() =>
      (super.noSuchMethod(
            Invocation.method(#startRingtone, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopRingtone() =>
      (super.noSuchMethod(
            Invocation.method(#stopRingtone, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> inviteToCall(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#inviteToCall, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> createOffer(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [remoteUserId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> createAnswer(
    String? remoteUserId,
    Map<String, dynamic>? offer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAnswer, [remoteUserId, offer]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRepository extends _i1.Mock implements _i8.CallRepository {
  MockCallRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CallEntity> createCall({
    required String? conversationId,
    required String? callerId,
    required String? receiverId,
    required _i2.CallType? type,
    Map<String, dynamic>? offer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCall, [], {
              #conversationId: conversationId,
              #callerId: callerId,
              #receiverId: receiverId,
              #type: type,
              #offer: offer,
            }),
            returnValue: _i6.Future<_i2.CallEntity>.value(
              _FakeCallEntity_0(
                this,
                Invocation.method(#createCall, [], {
                  #conversationId: conversationId,
                  #callerId: callerId,
                  #receiverId: receiverId,
                  #type: type,
                  #offer: offer,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.CallEntity>);

  @override
  _i6.Future<_i2.CallEntity?> getCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#getCall, [callId]),
            returnValue: _i6.Future<_i2.CallEntity?>.value(),
          )
          as _i6.Future<_i2.CallEntity?>);

  @override
  _i6.Future<List<_i2.CallEntity>> getActiveCalls(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCalls, [userId]),
            returnValue: _i6.Future<List<_i2.CallEntity>>.value(
              <_i2.CallEntity>[],
            ),
          )
          as _i6.Future<List<_i2.CallEntity>>);

  @override
  _i6.Future<_i2.CallEntity> acceptCall({
    required String? callId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptCall, [], {
              #callId: callId,
              #userId: userId,
            }),
            returnValue: _i6.Future<_i2.CallEntity>.value(
              _FakeCallEntity_0(
                this,
                Invocation.method(#acceptCall, [], {
                  #callId: callId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.CallEntity>);

  @override
  _i6.Future<void> declineCall(String? callId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#declineCall, [callId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.CallEntity> endCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#endCall, [callId]),
            returnValue: _i6.Future<_i2.CallEntity>.value(
              _FakeCallEntity_0(this, Invocation.method(#endCall, [callId])),
            ),
          )
          as _i6.Future<_i2.CallEntity>);

  @override
  _i6.Stream<_i2.CallEntity> watchCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCall, [callId]),
            returnValue: _i6.Stream<_i2.CallEntity>.empty(),
          )
          as _i6.Stream<_i2.CallEntity>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_1(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_4(this, Invocation.getter(#rest)),
          )
          as _i3.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i3.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_5(this, Invocation.getter(#auth)),
          )
          as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i3.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i3.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i3.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i3.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_6(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_7(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_8<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_9(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i3.RealtimeChannel>[],
          )
          as List<_i3.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i3.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_10(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i3.GoTrueAdminApi);

  @override
  _i3.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_11(this, Invocation.getter(#mfa)),
          )
          as _i3.GoTrueMFAApi);

  @override
  _i6.Stream<_i3.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i6.Stream<_i3.AuthState>.empty(),
          )
          as _i6.Stream<_i3.AuthState>);

  @override
  _i6.Stream<_i3.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i6.Stream<_i3.AuthState>.empty(),
          )
          as _i6.Stream<_i3.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i3.GoTrueAdminApi? value) => super.noSuchMethod(
    Invocation.setter(#admin, value),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i3.GoTrueMFAApi? value) => super.noSuchMethod(
    Invocation.setter(#mfa, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i3.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.OAuthResponse> getOAuthSignInUrl({
    required _i3.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i6.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.OAuthResponse>);

  @override
  _i6.Future<_i3.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i6.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i6.Future<_i3.AuthResponse> signInWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i3.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ResendResponse> resend({
    String? email,
    String? phone,
    required _i3.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i3.ResendResponse>.value(
              _FakeResendResponse_15(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.ResendResponse>);

  @override
  _i6.Future<_i3.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i6.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i6.Future<_i3.UserResponse>);

  @override
  _i6.Future<_i3.UserResponse> updateUser(
    _i3.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i6.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.UserResponse>);

  @override
  _i6.Future<_i3.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [refreshToken]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i6.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i6.Future<void> signOut({
    _i3.SignOutScope? scope = _i3.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i6.Future<List<_i3.UserIdentity>>.value(
              <_i3.UserIdentity>[],
            ),
          )
          as _i6.Future<List<_i3.UserIdentity>>);

  @override
  _i6.Future<_i3.AuthResponse> linkIdentityWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  _i6.Future<_i3.OAuthResponse> getLinkIdentityUrl(
    _i3.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i6.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.OAuthResponse>);

  @override
  _i6.Future<void> unlinkIdentity(_i3.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i6.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i3.AuthChangeEvent? event, {
    _i3.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_17(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);

  @override
  _i6.Future<_i3.GetClaimsResponse> getClaims([
    String? jwt,
    _i3.GetClaimsOptions? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getClaims, [jwt, options]),
            returnValue: _i6.Future<_i3.GetClaimsResponse>.value(
              _FakeGetClaimsResponse_18(
                this,
                Invocation.method(#getClaims, [jwt, options]),
              ),
            ),
          )
          as _i6.Future<_i3.GetClaimsResponse>);
}

/// A class which mocks [PQAuraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPQAuraService extends _i1.Mock implements _i10.PQAuraService {
  MockPQAuraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool hasSession(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#hasSession, [remoteUserId]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> getOrCreateSession(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateSession, [remoteUserId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> loadSession(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSession, [remoteUserId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i10.PQAuraEncryptedMessage?> encryptMessage(
    String? recipientId,
    String? plaintext,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptMessage, [recipientId, plaintext]),
            returnValue: _i6.Future<_i10.PQAuraEncryptedMessage?>.value(),
          )
          as _i6.Future<_i10.PQAuraEncryptedMessage?>);

  @override
  _i6.Future<Map<String, String>?> encryptMediaKey(
    String? recipientId,
    _i5.Uint8List? mediaKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptMediaKey, [recipientId, mediaKey]),
            returnValue: _i6.Future<Map<String, String>?>.value(),
          )
          as _i6.Future<Map<String, String>?>);

  @override
  _i6.Future<Map<String, String>?> encryptGroupMediaKey(
    List<String>? recipientIds,
    _i5.Uint8List? mediaKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptGroupMediaKey, [recipientIds, mediaKey]),
            returnValue: _i6.Future<Map<String, String>?>.value(),
          )
          as _i6.Future<Map<String, String>?>);

  @override
  _i6.Future<_i5.Uint8List?> decryptMediaKey(
    String? senderId,
    Map<String, dynamic>? encryptionData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMediaKey, [senderId, encryptionData]),
            returnValue: _i6.Future<_i5.Uint8List?>.value(),
          )
          as _i6.Future<_i5.Uint8List?>);

  @override
  _i6.Future<Map<String, String>?> encryptGroupMessage(
    List<String>? participantIds,
    String? plaintext,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptGroupMessage, [
              participantIds,
              plaintext,
            ]),
            returnValue: _i6.Future<Map<String, String>?>.value(),
          )
          as _i6.Future<Map<String, String>?>);

  @override
  _i6.Future<String?> decryptMessage(
    String? senderId,
    _i5.Uint8List? header,
    _i5.Uint8List? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMessage, [senderId, header, payload]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> closeSession(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#closeSession, [remoteUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSession(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [remoteUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
